#
# Rules for building subdir
#

ROOT_PATH := ../..

GEN_LIBS = libfcmd.a

#DEFINES += -D_POSIX_SOURCE

CCFLAGS += -Wno-pointer-to-int-cast -Wno-int-to-pointer-cast

#INCLUDES += -I $(ROOT_PATH)include

sinclude $(ROOT_PATH)/Makefile